# Generated by Django 4.2.5 on 2024-02-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
