# Generated by Django 4.2.5 on 2023-09-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_new_listing_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='bid',
        ),
    ]
