# Generated by Django 4.2.5 on 2023-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_bids_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_listing',
            name='category',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('J', 'Junk')], max_length=20),
        ),
    ]
