# Generated by Django 4.2.5 on 2023-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_new_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_listing',
            name='title',
            field=models.TextField(max_length=64),
        ),
    ]
