# Generated by Django 4.2.5 on 2023-09-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_new_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_listing',
            name='category',
            field=models.CharField(choices=[('NA', 'None'), ('N', 'New'), ('U', 'Used'), ('J', 'Junk')], max_length=20),
        ),
    ]
