# Generated by Django 4.2.5 on 2023-10-09 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_starting_bid_new_listing_bid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.new_listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.new_bid')),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.new_listing')),
            ],
        ),
        migrations.DeleteModel(
            name='bid',
        ),
    ]
