# Generated by Django 4.2.5 on 2023-10-09 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_new_bid_watchlist_delete_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='bid_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
