# Generated by Django 4.2.5 on 2023-11-05 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_new_listing_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('body', models.TextField(max_length=256)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
