# Generated by Django 4.2.5 on 2023-11-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_newcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcomment',
            name='listing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.new_listing'),
            preserve_default=False,
        ),
    ]
