# Generated by Django 4.2.5 on 2023-11-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_newcomment_listing_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewComment',
            new_name='New_Comment',
        ),
    ]
