# Generated by Django 4.2.5 on 2023-11-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_new_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_listing',
            name='closed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
