# Generated by Django 4.2.5 on 2023-11-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_new_listing_closed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
